### PR TITLE
feat(ssh): set sudo password from command with `--passcmd`

### PR DESCRIPTION
**Pull request by cafkafk**
Signed-off-by: Christina Sørensen <christina@cafkafk.com>

### CODE REVIEW

**Comment by 0z13** [comment]
discussed oob: probably want to keep pw out of process table

**Comment by johanot** [comment]
An "askpass"-helper would be fine imho, but that's not what this code does, is it?

**Comment by cafkafk** [comment]
> An "askpass"-helper would be fine imho, but that's not what this code does, is it?

not right now no

**Comment by cafkafk** [comment]
I'm planning to change this so you can supply some command to be run that gives a password, so I can use it with GNUPass

**Review by srhb — APPROVED** [review]

**Pull request merged**
