### PR TITLE
eval-machines: remove .drv file which pulls in unneeded deps

### PR DESCRIPTION
**Pull request by flokli**
all credit goes to @delroth - proposed in https://github.com/DBCDK/morph/issues/69#issuecomment-544610117

I'm running this since quite some time on my systems, and it's a huge time (and bandwidth)-saver.

### CODE REVIEW

**Comment by johanot** [comment]
Thanks for this!
It likely requires that we internally wrap morph with other build targets, since we actively use the drv on the target machines, but that's not your headache. :) We just need to do some testing real quick - I'll be back for a probable merge soon.

This definitely requires at least a release-note, but overall I think it this is a more sensible default for morph.

**Comment by flokli** [comment]
Great to hear! I agree this probably should be part of the release notes. I assume release notes are only on https://github.com/DBCDK/morph/releases, are they? Couldn't find those in the repo, otherwise I would have included in this PR ;-)

> morph stopped pushing `.drv` files to targets, only the nix paths, leading to a much smaller amount of data to be transferred.

**Comment by flokli** [comment]
@johanot small nag - any plans to do the next release?

**Comment by johanot** [comment]
@flokli better late than never :) https://github.com/DBCDK/morph/releases/tag/v1.4.0

**Comment by flokli** [comment]
Thanks a ton! nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/77431

**Pull request merged**
