### PR TITLE
Allow per deployment.nixPath .importPath

### PR DESCRIPTION
**Pull request by sorki**
Useful for mixing various version of nixpkgs and OSes.

See examples/pinning.nix

### CODE REVIEW

**Comment by sorki** [comment]
Different take on #34, similar to https://github.com/NixOS/nixops/pull/665/

**Comment by johanot** [comment]
@sorki Thanks for the PR! First glance looks good to me. 

To be honest, I was about to look into an adoption of the fix involving `pkgs.appendOverlays` as described in #34, since 19.03 is now stable. 

This PR doesn't solve #34 though? i.e. the `nixpkgs.pkgs` option will still be ignored, right?
Question is: How much do we care?

Personally, I'd like it better if we could get `nixpkgs.pkgs` to work as expected, but that comes with it's own set of drawbacks. I'm interested in hearing your opinion as well @Shados . :-)

**Comment by mmahut** [comment]
Just wanted to follow up on this pull request. What is needed to move this forward?

**Comment by sorki** [comment]
The company I wrote this for has no need for this anymore as they jumped to their own solution so this can be closed - I know of one user that still uses it but they can rely on my fork / overlay with this patch. Downsides of merging this is that it increases the complexity and when actually used it increases memory consumption quite a bit due to missing memoization during evaluation.

**Comment by mmilata** [comment]
This PR is obsoleted by #67, correct?

**Comment by sorki** [comment]
Pretty much, it's not completely the same as scoped imports but looks even more flexible.

**Pull request closed without merging**
