### PR TITLE
Add support for ports in hostnames

### PR DESCRIPTION
**Pull request by diamondburned**
Something like this:

```nix
{
    network = {
        inherit pkgs;
    };
    "root@192.168.1.169:737" = { config, pkgs, lib, ... }: {};
}
```

This has been tested with `morph deploy default.nix switch` only.

Side note: The go.mod PR should be completed (to prevent things like the second commit of this PR)

### CODE REVIEW

**Comment by johanot** [comment]
Thanks for the PR! You are very right about gomods.. Just haven't got the time for followinf it through, but.. Lets aim for it in the next release. :)

**Comment by johanot** [comment]
@diamondburned Just rebased with master and squashed to go.mod fixup. If you are happy with how the PR looks now, I'll be happy to merge. :)

**Comment by diamondburned** [comment]
I think it looks good to me.

**Comment by johanot** [comment]
This PR has been reverted due to lack of ipv6-support. Thanks @andir for catching that! 

@diamondburned I think that #112 for the most usecases solves the issue of "ssh-port-support" in morph, so I tend to want to leave it with that. But if you want to, feel free to look into extending this with ipv6-support and open a new PR. :)

**Comment by diamondburned** [comment]
If this change were to be applied, that address will also need to be changed according to https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers.

**Comment by diamondburned** [comment]
Playground demo: https://play.golang.org/p/77Fwas2cUvn

**Pull request merged**
