### PR TITLE
restore the defaults entry in the network file

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Review by cafkafk — CHANGES_REQUESTED** [review]
Thanks for your contribution! Could you elaborate a bit on what the motivation behind this PR is, and what it aims to accomplish? It makes it much easier to review  :)

**Comment by cleverca22** [comment]
nixops had a feature where you could specify a defaults entry in the network file, basically:

```nix
{
  defaults = {
    documentation.enable = false;
  };
  host1 = ...;
  host2 = ...;
}
```

and then nixos would merge defaults into every host

morph still has a blacklist to exclude defaults as a valid hostname, but doesnt actually merge it into each host, so it just silently discards this

the PR restores the functionality, so defaults works again

**Review by cafkafk — APPROVED** [review]
This looks good to me :+1: 

(ping @srhb for second opinion before merge)

**Comment by srhb** [comment]
agreed!

**Pull request merged**
