### PR TITLE
build(flake): flakify morph

### PR DESCRIPTION
**Pull request by cafkafk**
Signed-off-by: Christina Sørensen <christina@cafkafk.com>

### CODE REVIEW

**Comment by cafkafk** [comment]
Avoid rebase/squash merging (because it will ruin the hash of [4a3684b](https://github.com/DBCDK/morph/pull/211/commits/4a3684b18388d727f36a72f736f68ef379dbb209), breaking [9c70784](https://github.com/DBCDK/morph/pull/211/commits/9c70784568ce5e894ecbfc07b9b850fbbd68577c)), or notify me that you'd prefer to rebase/squash, and I'll follow up with a PR doing [9c70784](https://github.com/DBCDK/morph/pull/211/commits/9c70784568ce5e894ecbfc07b9b850fbbd68577c) after this merges, so the commit hash is locked in through this PR.

**Comment by cafkafk** [comment]
Found this PR which seems to have died https://github.com/DBCDK/morph/pull/153, should likely be closed if this merges.

**Review by srhb — APPROVED** [review]
Nice. I didn't know about the ignored revs feature, that's very handy.

**Comment by cafkafk** [comment]
> Nice. I didn't know about the ignored revs feature, that's very handy.

Nixpkgs also has one if you wanna see what kinda stuff they use it for: https://github.com/NixOS/nixpkgs/blob/master/.git-blame-ignore-revs :p

**Pull request merged**
