### PR TITLE
Convert the project to using Go modules

### PR DESCRIPTION
**Pull request by kalbasit**
This pull request proposes migrating the morph project to using [Go Modules](https://github.com/golang/go/wiki/Modules) and builds the project using [buildGoModule](https://kalbas.it/2019/03/17/announcing-the-new-golang-infrastructure-buildgomodule/).

### CODE REVIEW

**Comment by kalbasit** [comment]
Please squash & merge this PR, the commits are not master-quality. I can rebase the commits as well, but I'd rather have you write out the commit message. Thanks!

**Comment by adamtulinius** [comment]
Hi @kalbasit,

Thanks a lot for this, I appreciate you doing this work.

It's clear that go modules is the future, but (and I have a feeling that I also speak on behalf of @johanot when I say this) I know nothing at all about go modules, so we'll have to go read up on it before playing with this PR properly. I'll try to get a proper look of this during this week!

**Comment by kalbasit** [comment]
@adamtulinius absolutely! My main motivation for doing this work is to play with `buildGoModule` outside the nixpkgs to make sure that it works in some way similar to `buildGoPackage` with the added benefit of Go modules (I authored it on nixpkgs side). Please review this PR at your discretion. Also, feel free to push to it any changes that you see fit.

I am available if you have any questions.

Thank you!

**Comment by adamtulinius** [comment]
It sounds like go modules isn't going to be finalized before go 1.13, slated for release in august, so isn't it a bit premature to jump on the bandwagon already, especially considering nixos 19.03 only ships go 1.11, and not 1.12, which contain changes to how modules work?

**Comment by kalbasit** [comment]
@adamtulinius if your target is stable, then it might be too premature to merge this now. As I said previously, I was motivated by this change to make sure that `buildGoModule` works well outside of nixpkgs. As you can see in the pull request, I had to hardcode the default nixpkgs which is hardly the best way to do this.

**Comment by adamtulinius** [comment]
Yeah, we'll probably just hit the snooze button on this PR until we're closer to NixOS 19.09. Thanks for understanding :-)

**Comment by diamondburned** [comment]
I think that even though Go 1.13 isn't on Nix yet, it's safe to merge this PR. Most Go packages you see now will almost certainly have `go.mod`.

**Comment by grahamc** [comment]
Maybe nowish :)

**Comment by kalbasit** [comment]
I think it's time, yes. Should I rebase @adamtulinius ?

**Comment by adamtulinius** [comment]
> I think it's time, yes. Should I rebase @adamtulinius ?

That would be much appreciated, @kalbasit :)

**Comment by srhb** [comment]
I incorporated your changes in #148 and also dropped a bunch of our custom shell logic. Thank you!

**Pull request closed without merging**
