### PR TITLE
nix: use 'nix build' instead of 'nix-build' by default

### PR DESCRIPTION
**Pull request by johanot**
In the short term, this helps us solve our problems with 'extra-substituters' in nix v2.4. 
Setting `-v` by default gives us almost the same build log output as we had with `nix-build`.

Ideally this should be much more configurable, i.e. both verbosity level and the build command itself, but for now, nothing has changed in the configurability of morph in this regard. 

Switching to the nix 2 interface also seems inevitable for future improvements like flake support etc.

### CODE REVIEW

**Comment by srhb** [comment]
Looks correct to me, however: Are we sure that `nix build -f` behaves the same for nix 2.3 and nix 2.4(pre)? Those are the versions I assume we need to support, with permutations of `nix-command` and `nix-command flakes` enabled.

**Comment by johanot** [comment]
> Are we sure that nix build -f behaves the same for nix 2.3 and nix 2.4(pre)?

I only tested a few deployments with nix 2.4(pre). I assume that'll work with 2.3, but will test.

> ... assume we need to support, with permutations of nix-command and nix-command flakes enabled

I agree that we need to support those permutations, however we don't need to support building nixosConfigurations from flakes -yet. Will do some further testing.

**Comment by johanot** [comment]
Building works fine with both 2.3 and 2.4(pre), but the verbosity flag doesn't. You get the collapsed onelined progress view only with nix 2.3.

**Comment by srhb** [comment]
OK, that's fine I think :)

**Review by srhb — APPROVED** [review]

**Pull request merged**
