### PR TITLE
eval-machines: stop using deprecated evalConfig args

### PR DESCRIPTION
**Pull request by ckiee**
Fixes DBCDK/morph#180. 

I forgot about upstreaming this commit until @cole-h requested that. (thanks!)

-----
##### Build output
```
ckie@cookiemonster ~/git/morph -> ./result/bin/morph build examples/simple.nix
Selected 2/2 hosts (name filter:-0, limits:-0):
      0: db01.example.com (secrets: 0, health checks: 0, tags: db)
      1: web01.example.com (secrets: 0, health checks: 0, tags: web)
 
/nix/store/cqp27xg3i64dsanvh4gnn45h7dmz8v0l-morph
nix result path:
/nix/store/cqp27xg3i64dsanvh4gnn45h7dmz8v0l-morph
ckie@cookiemonster ~/git/morph -> ./result/bin/morph build examples/healthchecks.nix 2>&1 | tee build.log
Selected 1/1 hosts (name filter:-0, limits:-0):
      0: web01.example.com (secrets: 0, health checks: 3, tags: )
 
these 3 derivations will be built:
  /nix/store/f27fhz7xz9i046n2rsyvz9xdrapfy54v-healthcheck-commands.txt.drv
  /nix/store/7hmbl3q1v24mgal2v3vsfzjv6iwfk31j-nixos-system-web01.example.com-20.03post-git.drv
  /nix/store/7m2mccs276r5ak676hgzqv5dxm4amab3-morph.drv
building '/nix/store/f27fhz7xz9i046n2rsyvz9xdrapfy54v-healthcheck-commands.txt.drv'...
building '/nix/store/7hmbl3q1v24mgal2v3vsfzjv6iwfk31j-nixos-system-web01.example.com-20.03post-git.drv'...
building '/nix/store/7m2mccs276r5ak676hgzqv5dxm4amab3-morph.drv'...
/nix/store/s4n8kcjvwyaj98plx58vdm7vk2606bb7-morph
nix result path:
/nix/store/s4n8kcjvwyaj98plx58vdm7vk2606bb7-morph
```

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
Works for me! Gets rid of all the red text when I deploy -- thanks!

cc @srhb or anybody else with commit access -- would be lovely to get this in :)

**Comment by ckiee** [comment]
A few PRs [seem to be stale](https://github.com/DBCDK/morph/pulls?q=is%3Apr+is%3Aopen+review%3Arequired).

**Comment by cole-h** [comment]
Here's hoping I have the magic ping, then :^)

**Comment by srhb** [comment]
You are not forgotten, I will get to it ASAP. :heart:

**Comment by srhb** [comment]
Thank you! :smile:

**Comment by cole-h** [comment]
Thank *you*!

**Pull request merged**
